/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CreateIndexRouteImport } from "./routes/create/index"
import { Route as TimerIdIndexRouteImport } from "./routes/$timerId/index"
import { Route as TimerIdEditRouteImport } from "./routes/$timerId/edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRouteImport,
} as any)
const TimerIdIndexRoute = TimerIdIndexRouteImport.update({
  id: "/$timerId/",
  path: "/$timerId/",
  getParentRoute: () => rootRouteImport,
} as any)
const TimerIdEditRoute = TimerIdEditRouteImport.update({
  id: "/$timerId/edit",
  path: "/$timerId/edit",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId": typeof TimerIdIndexRoute
  "/create": typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId": typeof TimerIdIndexRoute
  "/create": typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$timerId/edit": typeof TimerIdEditRoute
  "/$timerId/": typeof TimerIdIndexRoute
  "/create/": typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/$timerId/edit" | "/$timerId" | "/create"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$timerId/edit" | "/$timerId" | "/create"
  id: "__root__" | "/" | "/$timerId/edit" | "/$timerId/" | "/create/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimerIdEditRoute: typeof TimerIdEditRoute
  TimerIdIndexRoute: typeof TimerIdIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create/": {
      id: "/create/"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$timerId/": {
      id: "/$timerId/"
      path: "/$timerId"
      fullPath: "/$timerId"
      preLoaderRoute: typeof TimerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$timerId/edit": {
      id: "/$timerId/edit"
      path: "/$timerId/edit"
      fullPath: "/$timerId/edit"
      preLoaderRoute: typeof TimerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimerIdEditRoute: TimerIdEditRoute,
  TimerIdIndexRoute: TimerIdIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
